# This file would likely be external to this repo and be managed by the platform team

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-services
  namespace: argocd # The namespace argocd is installed in
spec:
  generators:
    - merge:
        mergeKeys:
          - '{{path[1]}}'
        generators:
          - git:
              repoURL: "https://github.com/josh-thisisbud/platform-config-demo.git"
              revision: main
              directories:
              - path: '/develop/**/service.yaml'
          - git:
              repoURL: "https://github.com/josh-thisisbud/platform-config-demo.git"
              revision: main
              directories:
              - path: '/develop/**/aviva/overrides.yaml'
  template:
    metadata:
      name: '{{namespace}}-{{path[1]}}'
    spec:
      project: "bud"
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'